export const teluguRelations = [
    { relation: "atta", english: "Aunt (Father's Sister)", pronunciation: "a-tta" },
    { relation: "doDDamma", english: "Aunt (Mother's elder Sister)", pronunciation: "do-DDa-mma" },
    { relation: "pinni", english: "Aunt (Mother's younger Sister)", pronunciation: "pi-nni" },
    { relation: "anna", english: "Elder Brother", pronunciation: "a-nna" },
    { relation: "tammuDu", english: "Younger Brother", pronunciation: "ta-mmu-Du" },
    { relation: "bAva gAru", english: "Brother-in-law (Husband's Older Brother)", pronunciation: "bA-va gA-ru" },
    { relation: "annayya gAru", english: "Brother-in-law (Husband's Sister's Husband)", pronunciation: "a-nna-yya gA-ru" },
    { relation: "maridi", english: "Brother-in-law (Husband's Younger Brother)", pronunciation: "ma-ri-di" },
    { relation: "bAvamaridi", english: "Brother-in-law (Wife's Brother)", pronunciation: "bA-va-ma-ri-di" },
    { relation: "kUturu", english: "Daughter", pronunciation: "kU-tu-ru" },
    { relation: "kODalu", english: "Daughter-in-law", pronunciation: "kO-Da-lu" },
    { relation: "nAnna", english: "Father", pronunciation: "nA-nna" },
    { relation: "mAva-gAru", english: "Father-in-law", pronunciation: "mA-va-gA-ru" },
    { relation: "manavarAlu", english: "Granddaughter", pronunciation: "ma-na-va-rA-lu" },
    { relation: "tAta", english: "Grandfather", pronunciation: "tA-ta" },
    { relation: "mAmma", english: "Grandmother (Father's Mother)", pronunciation: "mA-mma" },
    { relation: "ammamma", english: "Grandmother (Mother's Mother)", pronunciation: "a-mma-mma" },
    { relation: "manavaDu", english: "Grandson", pronunciation: "ma-na-va-Du" },
    { relation: "bharta", english: "Husband", pronunciation: "bha-rta" },
    { relation: "amma", english: "Mother", pronunciation: "a-mma" },
    { relation: "atta", english: "Mother-in-law", pronunciation: "a-tta" },
    { relation: "mEnalluDu", english: "Nephew (Sister's Son)", pronunciation: "mE-na-llu-Du" },
    { relation: "mEnagODalu", english: "Niece (Sister's Daughter)", pronunciation: "mE-na-gO-Da-lu" },
    { relation: "baMdhuvu", english: "Relative", pronunciation: "baM-dhu-vu" },
    { relation: "akka", english: "Elder Sister", pronunciation: "a-kka" },
    { relation: "celli", english: "Younger Sister", pronunciation: "ce-lli" },
    { relation: "vadina", english: "Sister-in-law (Brother's Wife)", pronunciation: "va-di-na" },
    { relation: "maradalu", english: "Sister-in-law (Wife's Sister)", pronunciation: "ma-ra-da-lu" },
    { relation: "koDuku", english: "Son", pronunciation: "ko-Du-ku" },
    { relation: "alluDu", english: "Son-in-law", pronunciation: "a-llu-Du" },
    { relation: "peddanAnna", english: "Uncle (Father's Older Brother)", pronunciation: "pe-dda-nA-nna" },
    { relation: "mAvayya", english: "Uncle (Father's Sister's Husband)", pronunciation: "mA-va-yya" },
    { relation: "cinnAnna", english: "Uncle (Father's Younger Brother)", pronunciation: "ci-nna-nna" },
    { relation: "mAma", english: "Uncle (Mother's Brother)", pronunciation: "mA-ma" },
    { relation: "bhArya", english: "Wife", pronunciation: "bhA-rya" },
  ];